#!/usr/bin/env python3
"""Generate a C++ header embedding a .vcshader file's raw text as a string literal.

Usage: embed_shader.py <input.vcshader> <output.h> <identifier>

Emits a header defining `inline constexpr const char* <identifier>` under the
Vectrix::EmbeddedShaders namespace, holding the shader's source as a raw string
literal, so the engine can compile it in instead of reading it from disk at runtime.
"""
import sys

DELIMITER = "VCSHADER"


def main() -> int:
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <input.vcshader> <output.h> <identifier>", file=sys.stderr)
        return 1

    input_path, output_path, identifier = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(input_path, "r", encoding="utf-8") as f:
        content = f.read()

    closing = f"){DELIMITER}\""
    if closing in content:
        print(f"error: {input_path} contains the raw-string delimiter '{closing}'", file=sys.stderr)
        return 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("#pragma once\n\n")
        f.write("// Auto-generated by Vectrix/scripts/embed_shader.py — do not edit by hand.\n")
        f.write(f"// Source: {input_path}\n\n")
        f.write("namespace Vectrix::EmbeddedShaders {\n")
        f.write(f'    inline constexpr const char* {identifier} = R"{DELIMITER}(\n')
        f.write(content)
        f.write(f'){DELIMITER}";\n')
        f.write("} // Vectrix::EmbeddedShaders\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
